### ISSUE TITLE
filename for stlink source zip has changed, causing vagrant provisioning to fail

### ISSUE THREAD

**Issue by philmcm** [pichenettes/mutable-dev-environment#4]
The filename for stlink source zip in texane github has changed, causing vagrant provisioning to fail.

Modifying 0_install-toolchain.sh and adding a "v" in front of the filename fixes it.

The two lines which need to be changed are in the #install stlink section

wget -nv https://github.com/texane/stlink/archive/v1.1.0.tar.gz
tar xfz v1.1.0.tar.gz

I have manually modified the file and reprovisioned and verified that the stlink source downloads and installs correctly.

**Comment by pichenettes** [comment]
Thanks, it's now fixed!
