### ISSUE TITLE
Cannot upload programming for Clouds

### ISSUE THREAD

**Issue by denniskulpa** [pichenettes/mutable-dev-environment#5]
I just finished building a Clouds module, it was a full kit that I purchased from synthCube.  The STM chip was supposed to be pre-flashed but the module does not do anything upon power-up.  I have set up the VirtualBox/Vagrant environment on my computer (MacMini running Sierra), using an STLink V2 with an Olimex ARM-JTAG-20-10 to connect to the module.  When I try to upload this is what I get:

vagrant@vagrant-ubuntu-trusty-64:/vagrant/eurorack-modules$ make -f clouds/makefile upload_combo_jtag
openocd -s /opt/local/share/openocd/scripts/ -f interface/stlink-v2.cfg -f target/stm32f4x.cfg -c "init" -c "halt" -c "sleep 200" \
				-f stmlib/programming/jtag/erase_f4xx.cfg \
				-c "flash write_image erase build/clouds/clouds_bootloader_combo.bin 0x08000000" \
				-c "verify_image build/clouds/clouds_bootloader_combo.bin 0x08000000" \
				-c "sleep 200" -c "reset run" -c "shutdown"
Open On-Chip Debugger 0.9.0 (2020-08-25-19:04)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v29 API v2 SWIM v7 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 3.007456
Error: init mode failed (unable to connect to the target)
in procedure 'init' 
in procedure 'ocd_bouncer'

make: *** [upload_combo_jtag] Error 1

It appears that the computer is not seeing the processor.  I have gone over the entire PCB several times, touched up several solder connections, checked continuity and routing against the circuit schematic and I can't find any errors.  Does this mean that the processor chip is bad or is there some other communication error in play here??

TIA,
Dennis Kulpa

**Comment by pichenettes** [comment]
This page is for reporting issues with the codebase, not to solve problems with a specific DIY build.

Please contact the maker/seller of your DIY kit (SynthCube) for any assistance. Mutable Instruments does not endorse, support (and profit from) the distribution of its designs as DIY kits.

**Comment by denniskulpa** [comment]
OK, sorry.  I'm relatively new here, I just wanted to be sure I wasn't doing something wrong with the programming.
